# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target '24-MosaicLayOut' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 24-MosaicLayOut

pod 'TRMosaicLayout'

end
